[package]
edition = '2024'
name = "ocpp-charge-point"
version = "0.1.0"
description = "OCPP Charge Point Implementation. Use this library to implement an OCPP charge point"
repository = "https://github.com/flowionab/ocpp-charge-point"
license = "MIT OR Apache-2.0"
authors = ["Joatin Granlund <joatin@granlund.io>"]
keywords = ["OCPP", "CP", "ChargePoint", "ocpp16", "ocpp201"]

[features]
std = []
default = ["ocpp_1_6", "ocpp_2_0_1"]
ocpp_1_6 = ["ocpp-client/ocpp_1_6"]
ocpp_2_0_1 = ["ocpp-client/ocpp_2_0_1"]

[dependencies]
tokio = { version = "1", features = ["rt", "sync", "time"] }
ocpp-client = { git = "https://github.com/flowionab/ocpp-client" }
async-trait = "^0.1"
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1.39", features = ["full"]}
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
